---

- name: delete {{ oai.docker.container.ue_image }} container
  community.docker.docker_container:
    name: "rfsim5g-oai-nr-ue"
    state: absent
  when: inventory_hostname in groups['oai_nodes'][0]
  become: true

- name: remove /tmp/oai-ue.conf
  file:
    path: "/tmp/oai-ue.conf"
    state: absent
  when: inventory_hostname in groups['oai_nodes'][0]
  become: true
